---
title: "1_ComputeRepeatability"
author: "Ghais ZRIKI, Nicolas RODE"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document: 
    number_sections: yes
    theme: journal
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```

# Load and check count data
## Load count data 
```{r }
## Load count data for each observer
data <- readxl::read_excel(path=file.path(here::here(), "data", "raw_data", "DS_Counting_trials.xlsx"), sheet = "ObserverCountData")
## Load true counts for each sample
truecounts <- readxl::read_excel(path=file.path(here::here(), "data", "raw_data", "DS_Counting_trials.xlsx"), sheet = "TrueCounts")
head(data)
#View(data)
dim(data)
#View(truecounts)
head(truecounts)

## Convert as factor
data$Person.ID <- as.factor(data$Observer_ID)
data$Sample_ID <- as.factor(data$Sample_ID)
data$Incubation <- as.factor(data$Incubation)

```
## Check data
```{r }
## Check that 2 replicates per Observer_ID and Sample_ID
data %>%
  dplyr::select(Observer_ID, Sample_ID) %>% 
  dplyr::group_by(Observer_ID, Sample_ID) %>%
  dplyr::summarise(Count=length(Sample_ID)) %>%
  print(n = 300)
```
## Table 1: sumarize data
```{r}
summary_time <- data %>%
  dplyr::mutate(Counting_error = abs(Obs_No_Larvae - True_No_Larvae), Category_True_No_Larvae=as.factor(cut(True_No_Larvae, breaks=c(0, 5, 10, 15, Inf), labels=c("0-5","5-10","10-15","+15"), right = FALSE))) %>%
  dplyr::select(Previous_Experience, Counting_error, Time_Sec, Incubation, Round, Category_True_No_Larvae) %>%
  dplyr::group_by( Incubation, Previous_Experience, Category_True_No_Larvae) %>%
  dplyr::summarise(Counting_error_mean=mean(Counting_error), Time_Sec_mean=mean(Time_Sec), standard_deviation = sd(Time_Sec), N = length(Time_Sec)) %>% dplyr::mutate(standard_error=standard_deviation/sqrt(N)) %>%
 dplyr::relocate(Category_True_No_Larvae, .before = Incubation) %>%
 dplyr::relocate(standard_error, .before = N) %>%
 dplyr::arrange(Incubation, Previous_Experience, Category_True_No_Larvae) %>% dplyr::mutate(dplyr::across(Counting_error_mean:standard_error, round, 2))

## Check the levels for Category_True_No_Larvae
levels(summary_time$Category_True_No_Larvae)

## Export table
##write.table(x=summary_time, file=file.path("data", "derived_data", "summary_counting_time.csv"), row.names = FALSE, sep=";")

```
# Repeatability
```{r }
## Mixed model
m0 <- lme4::lmer(log(Obs_No_Larvae+1)~1+(1|Sample_ID)+(1|Person.ID), data=data, REML = TRUE)
summary(m0)

## -(1|Person.ID)
m1 <- lme4::lmer(log(Obs_No_Larvae+1)~1+(1|Sample_ID), data=data, REML = TRUE)
summary(m1)
anova(m0, m1, test="Chisq")

## Extract variance components
VAR <- as.data.frame(lme4::VarCorr(m0))$vcov

## Compute repeatability among observers
RepeatabilityAmong <- VAR[1]/sum(VAR)
## Compute repeatability within observers
RepeatabilityWithin <-VAR[1]/sum(VAR[c(1, 3)])
```
# Time for counting larvae
## Plots
```{r }
## Histogram with time
ggplot(data, aes(x=log(Time_Sec))) + 
  geom_histogram(binwidth=1)


## Time used for counting as a function of number of larvae
p1 <- data %>%
  dplyr::mutate(Category_True_No_Larvae=cut(True_No_Larvae, breaks=c(0, 5, 10, 15, Inf), labels=c("0-5","5-10","10-15","+15"), right = FALSE)) %>%
  dplyr::select(Category_True_No_Larvae, Incubation, Time_Sec) %>%
  ggplot(aes(x=Category_True_No_Larvae,  y=Time_Sec, color=Incubation)) + geom_boxplot() + xlab("Expected number of larvae") + ylab("Time for counting larvae (sec.)") + scale_color_discrete(name = "48h-incubation")

p1
title_plot <- "Fig1_Time_Expected_No_Larvae.png"
cowplot::save_plot(file =here::here("plots", title_plot),
                 p1, base_height = 10/cm(1),
                  base_width = 12.5/cm(1), dpi = 1200)



```
## Analyses
```{r }
## Step1:Complete model
m0 <- lme4::lmer(log(Time_Sec)~Incubation*True_No_Larvae+Previous_Experience+Round+(1|Sample_ID)+(1|Person.ID), data=data)
summary(m0)

## -Incubation*True_No_Larvae
m1 <- lme4::lmer(log(Time_Sec)~Incubation+True_No_Larvae+Round+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)

anova(m0, m1, test="Chisq")

## -Previous_Experience
m2 <- lme4::lmer(log(Time_Sec)~Incubation*True_No_Larvae+Round+(1|Sample_ID)+(1|Person.ID), data=data)
summary(m2)

anova(m0, m2, test="Chisq")

## -Round
m3 <- lme4::lmer(log(Time_Sec)~Incubation*True_No_Larvae+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)

anova(m0, m3, test="Chisq")


## Step2: We continue with the model with highest P-value (m1) and test for each remaining fixed effects

## -Previous_Experience
m4 <- lme4::lmer(log(Time_Sec)~Incubation+True_No_Larvae+Round+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m1, m4, test="Chisq")

## -Round
m5 <- lme4::lmer(log(Time_Sec)~Incubation+True_No_Larvae+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m1, m5, test="Chisq")

## -Incubation
m6 <- lme4::lmer(log(Time_Sec)~True_No_Larvae+Round+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m1, m6, test="Chisq")

## -True_No_Larvae
m7 <- lme4::lmer(log(Time_Sec)~Incubation+Round+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)
summary(m7)
anova(m1, m7, test="Chisq")

## Step3: We continue with the model with highest P-value (m6) and test for each remaining fixed effects

## -True_No_Larvae
m8 <- lme4::lmer(log(Time_Sec)~Round+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m6, m8, test="Chisq")

## -Round
m9 <- lme4::lmer(log(Time_Sec)~True_No_Larvae+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m6, m9, test="Chisq")

## -Previous_Experience
m10 <- lme4::lmer(log(Time_Sec)~True_No_Larvae+Round+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m6, m10, test="Chisq")

## Step3: We continue with the model with highest P-value (m10) and test for each remaining fixed effects

## -True_No_Larvae
m11 <- lme4::lmer(log(Time_Sec)~Round+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m10, m11, test="Chisq")

## -Round
m12 <- lme4::lmer(log(Time_Sec)~True_No_Larvae+(1|Sample_ID)+(1|Person.ID), data=data)
anova(m10, m12, test="Chisq")

## step4: Compute the final p-values of effect that have been removed
## +Incubation
m13 <- lme4::lmer(log(Time_Sec)~Incubation*factor(True_No_Larvae)+Round+(1|Sample_ID)+(1|Person.ID), data=data)
summary(m13)
anova(m13, m10, test="Chisq")

## Check residuals
ggplot() +
  aes(x=residuals(m10))+ 
  geom_histogram(binwidth=0.1)
```
# Mean Square Count Error (MSE)
## Compute Squared count error and Mean squared count error
```{r }
## Check difference between Obs_No_Larvae and True_No_Larvae
data %>%
  dplyr::mutate(Counting_error = abs(Obs_No_Larvae - True_No_Larvae)) %>% 
  dplyr::select(Previous_Experience, Counting_error, Time_Sec, Incubation, Round) %>% 
  dplyr::group_by( Incubation, Previous_Experience, Round) %>%
  dplyr::summarise(Counting_error_mean=mean(Counting_error),
            Time_Sec_mean=mean(Time_Sec),
            Time_Sec_median=median(Time_Sec))

## Compute Squared Error
Squared_error_data <- data %>%
  dplyr::mutate(Count_error_squared = (Obs_No_Larvae - True_No_Larvae)^2) 

## Compute MSE by sampleID
Squared_error_data %>%
  dplyr::select(Sample_ID, Previous_Experience, Count_error_squared, Incubation, Round) %>% 
    dplyr::group_by(Sample_ID) %>%
  dplyr::summarise(MSE=mean(Count_error_squared))

## Compute MSE by sampleID and incubation
MSE_bysampleIDincubation <- data %>%
  dplyr::mutate(Count_error_squared = (Obs_No_Larvae - True_No_Larvae)^2) %>%
  dplyr::select(Sample_ID, Obs_No_Larvae, True_No_Larvae, Count_error_squared, Incubation) %>% 
  dplyr::group_by(Sample_ID, Incubation) %>%
  dplyr::summarise(Mean_Obs_No_Larvae=mean(Obs_No_Larvae), Sum_Obs_No_Larvae=sum(Obs_No_Larvae), True_No_Larvae=mean(True_No_Larvae), Sum_Count_error_squared=sum(Count_error_squared), N=length(Count_error_squared), Var_Obs_No_Larvae=var(Obs_No_Larvae)) %>%
  dplyr::mutate(SquaredBias_Obs_No_Larvae = (Mean_Obs_No_Larvae - True_No_Larvae)^2, Var_Obs_No_Larvae = Var_Obs_No_Larvae*(N-1)/N, MSE = Sum_Count_error_squared/N)%>%
  dplyr::mutate(propBias = SquaredBias_Obs_No_Larvae/MSE) %>%
  print(n = 30)

## Compute MSE by sampleID and incubation and experience
MSE_bysampleIDincubationExperience <- data %>%
  dplyr::mutate(Count_error_squared = (Obs_No_Larvae - True_No_Larvae)^2) %>%
  dplyr::select(Sample_ID, Previous_Experience, Obs_No_Larvae, True_No_Larvae, Count_error_squared, Incubation) %>% 
  dplyr::group_by(Sample_ID, Incubation, Previous_Experience) %>%
  dplyr::summarise(Mean_Obs_No_Larvae=mean(Obs_No_Larvae), Sum_Obs_No_Larvae=sum(Obs_No_Larvae), True_No_Larvae=mean(True_No_Larvae), Sum_Count_error_squared=sum(Count_error_squared), N=length(Count_error_squared), Var_Obs_No_Larvae=var(Obs_No_Larvae)) %>%
  dplyr::mutate(SquaredBias_Obs_No_Larvae = (Mean_Obs_No_Larvae - True_No_Larvae)^2, Var_Obs_No_Larvae = Var_Obs_No_Larvae*(N-1)/N, MSE = Sum_Count_error_squared/N)%>%
  print(n = 60)

## Compute MSE by sampleID and incubation and experience and Round
MSEdataRoundExperience <- data %>%
  dplyr::mutate(Count_error_squared = (Obs_No_Larvae - True_No_Larvae)^2) %>%
  dplyr::select(Sample_ID, Round, Previous_Experience, Obs_No_Larvae, True_No_Larvae, Count_error_squared, Incubation) %>% 
  dplyr::group_by(Sample_ID, Round, Incubation, Previous_Experience) %>%
  dplyr::summarise(Mean_Obs_No_Larvae=mean(Obs_No_Larvae), Sum_Obs_No_Larvae=sum(Obs_No_Larvae), True_No_Larvae=mean(True_No_Larvae), Sum_Count_error_squared=sum(Count_error_squared), N=length(Count_error_squared), Var_Obs_No_Larvae=var(Obs_No_Larvae)) %>%
  dplyr::mutate(SquaredBias_Obs_No_Larvae = (Mean_Obs_No_Larvae - True_No_Larvae)^2, Var_Obs_No_Larvae = Var_Obs_No_Larvae*(N-1)/N, MSE = Sum_Count_error_squared/N)%>%
  print(n = 60)

```

## Plots
```{r }

p2 <- MSE_bysampleIDincubation %>%
  dplyr::mutate(Category_True_No_Larvae=cut(True_No_Larvae, breaks=c(0, 5, Inf), labels=c("0-5","+5"), right = FALSE)) %>%
  ggplot(aes(x=Category_True_No_Larvae, y=sqrt(MSE), color=Incubation)) + geom_boxplot() +
  xlab("Number of larvae") + ylab(expression(sqrt("Mean count error"))) + scale_color_discrete(name = "48h-incubation")
p2
title_plot <- "Fig2_CountErrorbyNumLarvaeandIncubation.png"
cowplot::save_plot(file =here::here("plots", title_plot),
                 p2, base_height = 10/cm(1),
                  base_width = 12.5/cm(1), dpi = 1200)


## Relationship between expected and observed number of larvae
pS1 <- data %>%
  dplyr::select(Obs_No_Larvae, True_No_Larvae, Incubation, Round) %>%
  ggplot(aes(x=True_No_Larvae, Obs_No_Larvae, color=Incubation)) + geom_point() + xlim(0, 35) + ylim(0, 35) + geom_abline(intercept = 0, slope = 1)+ xlab("Expected number of larvae") + ylab("Observed number of larvae") + scale_color_discrete(name = "48h-incubation")
pS1

title_plot <- "FigS1_Observed_Expected_No_Larvae.png"
cowplot::save_plot(file =here::here("plots", title_plot),
                 pS1, base_height = 10/cm(1),
                  base_width = 12.5/cm(1), dpi = 1200)


## Error for replicate A or B
pS2 <- MSEdataRoundExperience %>%
  dplyr::mutate(Category_True_No_Larvae=cut(True_No_Larvae, breaks=c(0, 5, 10, 15, Inf), labels=c("0-5","5-10","10-15","+15"), right = FALSE)) %>%
  ggplot(aes(x=Category_True_No_Larvae, y=sqrt(MSE), color=Round)) + geom_boxplot() + xlab("Number of larvae") + ylab(expression(sqrt("Mean count error")))
pS2
title_plot <- "FigS2_CountErrorbyReplicate.png"
cowplot::save_plot(file = here::here("plots", title_plot),
                 pS2, base_height = 10/cm(1),
                  base_width = 12.5/cm(1), dpi = 1200)

## MSE as a function of true number of larvae
pS3 <- Squared_error_data %>%
  dplyr::select(Count_error_squared, True_No_Larvae, Incubation) %>%
  ggplot(aes(x=True_No_Larvae, sqrt(Count_error_squared), color=Incubation)) + geom_point() + xlab("Expected number of larvae") + ylab(expression(sqrt("Mean count error")))
pS3

```
## Analyses
```{r}

## Step1:Complete model
m0 <- lme4::lmer(sqrt(Count_error_squared)~Incubation*True_No_Larvae+Previous_Experience+Round+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

summary(m0)

## -Incubation*True_No_Larvae
m1 <- lme4::lmer(sqrt(Count_error_squared)~Incubation+True_No_Larvae+Previous_Experience+Round+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

anova(m0, m1, test="Chisq")

## -Round
m2 <- lme4::lmer(sqrt(Count_error_squared)~Incubation*True_No_Larvae+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

anova(m0, m2, test="Chisq")

## -Previous_Experience
m3 <- lme4::lmer(sqrt(Count_error_squared)~Incubation*True_No_Larvae+Round+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

anova(m0, m3, test="Chisq")

## Step2: We continue with the model with highest P-value (m3) and test for each remaining fixed effects

##-Incubation*True_No_Larvae
m4 <- lme4::lmer(sqrt(Count_error_squared)~Incubation+True_No_Larvae+Round+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

anova(m3, m4, test="Chisq")

## -Round
m5 <- lme4::lmer(sqrt(Count_error_squared)~Incubation*True_No_Larvae+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)
summary(m5)
anova(m3, m5, test="Chisq")

## Step3: We continue with the model with highest P-value (m5) and test for each remaining fixed effects
## -Incubation*True_No_Larvae
m6 <- lme4::lmer(sqrt(Count_error_squared)~Incubation+True_No_Larvae+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)
anova(m5, m6, test="Chisq")

## step4: Compute the p-values of effect that have been removed
## +Previous_Experience
m7 <- lme4::lmer(sqrt(Count_error_squared)~Incubation*True_No_Larvae+Previous_Experience+(1|Sample_ID)+(1|Person.ID), data=Squared_error_data)

anova(m5, m7, test="Chisq")

## Histogram with time
ggplot()+ aes(x=residuals(m5)) + 
  geom_histogram(binwidth=0.25)

```
# Test for differences between incubated and non incubated samples
```{r}
## Check for an absence of differences in the number of larvae between incubated and non incubated samples

## Check the mean number of larvae for samples with 48h of incubation or not
truecounts %>%
  dplyr::group_by(Incubation) %>%
  dplyr::summarise(True_No_Larvae_mean=mean(True_No_Larvae), True_No_Larvae_median=median(True_No_Larvae))

m <- glm(True_No_Larvae~Incubation, data=truecounts, family="poisson")
summary(m)

```
